version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sparkboard-lambda-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ujest76o1p18"
s3_prefix = "sparkboard-lambda-dev"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"

